coderia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('community.urls')),
    path('note', include('note.urls')),
    path('admin/', admin.site.urls),
    path('search/', include('haystack.urls')),
]

note/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static

app_name = 'note'

urlpatterns = [
    path('video_note/', views.video_note, name='video_note'),
    path('code_note/', views.code_note, name='code_note'),
    path('show_notes/', views.show_notes, name='show_notes'),
    path('note_detail/<note_id>/', views.note_detail, name='note_detail'),
    path('save_comment/', views.save_comment, name='save_comment'),
    path('get_reply/', views.get_reply, name='get_reply'),
    path('upload_video/', views.upload_video, name='upload_video'),
    path('code_editor/', views.code_editor, name='code_editor'),
    path('edit_note/<note_id>/', views.edit_note, name='edit_note'),
]

# urlpatterns += static(settings)

templates/search/search.html
{% extends "base.html" %}

{% load highlight %}

{% block style %}
    <style>
        span.highlighted {
            color: #ab801d;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="page-content bg-white">
        <div class="content-block">
            <!-- About Us -->
            <div class="section-full bg-white content-inner-2">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-7 col-sm-12 col-12">
                            <div class="row loadmore-content">
                                <div class="col-lg-12" style="margin-top: 100px">
                                    {% if query %}
                                        {% for result in page.object_list %}
                                            <div name="note_detail" class="blog-card blog-md"
                                                 onclick="window.location.href='{% url 'note:note_detail' result.object.note_id %}'">
                                                <div class="blog-card-media">
                                                    <img src="/static/images/blog/grid/pic5.jpg" alt=""/>
                                                </div>
                                                <div class="blog-card-info">
                                                    <h4 class="title">
                                                        <a>{% highlight result.object.title with query %}</a>
                                                    </h4>
                                                    <p>
                                                        {{ result.object.create_time|timesince }} ago
                                                        <a style="font-weight: bold">written
                                                            by {{ result.object.uid.username }}</a>
                                                    </p>
                                                    <p>
                                                        {% if result.object.content_html %}
                                                            {% highlight result.object.content_html with query %}
                                                        {% else %}
                                                            {% highlight result.object.content with query %}
                                                        {% endif %}
                                                    </p>
                                                    <a class="btn-link readmore">
                                                        <i class="la la-arrow-right"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- About Us End -->
        </div>
    </div>
{% endblock %}